export const posts = [
  // 🧠 Technology
  {
    id: "tech-post-1",
    title: "How AI is Changing the World",
    description:
      "Discover how artificial intelligence is revolutionizing industries, from healthcare to finance.",
    category: "technology",
    author: "Jane Doe",
    publishedDate: "2025-04-15",
    readingTime: "5 min",
    image: "/images/posts/ai-world.jpg",
    tags: ["AI", "Future", "Innovation"],
    content: `Artificial Intelligence (AI) is transforming every industry. From healthcare diagnostics to financial predictions, AI tools are helping organizations make smarter decisions...`,
  },
  {
    id: "tech-post-2",
    title: "Top 5 JavaScript Frameworks in 2025",
    description:
      "Explore the most popular frameworks developers are using this year.",
    category: "technology",
    author: "Ali Youssef",
    publishedDate: "2025-02-20",
    readingTime: "4 min",
    image: "/images/posts/js-frameworks.jpg",
    tags: ["JavaScript", "Frameworks", "Frontend"],
    content: `JavaScript continues to evolve, and 2025 has introduced several powerful frameworks. This post compares the top 5 based on speed, community support, and ease of use.`,
  },
  {
    id: "tech-post-3",
    title: "Building Secure Web Apps",
    description:
      "A guide to keeping your applications secure and protected from modern threats.",
    category: "technology",
    author: "Sara Lee",
    publishedDate: "2025-03-10",
    readingTime: "6 min",
    image: "/images/posts/secure-web-apps.jpg",
    tags: ["Security", "Web", "Best Practices"],
    content: `Web app security is more important than ever. In this guide, we'll cover the best practices for protecting your applications from common vulnerabilities.`,
  },
  {
    id: "tech-post-4",
    title: "Understanding Cloud Computing",
    description:
      "Learn the basics of cloud services and how to choose the right provider.",
    category: "technology",
    author: "Mohamed Ashraf",
    publishedDate: "2025-01-28",
    readingTime: "7 min",
    image: "/images/posts/cloud-computing.jpg",
    tags: ["Cloud", "Infrastructure", "AWS"],
    content: `Cloud computing has changed how we host and scale applications. This post explores different types of cloud services and how to pick the right one.`,
  },

  // 🏥 Health
  {
    id: "health-post-1",
    title: "Top 10 Healthy Habits for a Better Life",
    description:
      "Improve your well-being with these science-backed daily habits.",
    category: "health",
    author: "Emily Clark",
    publishedDate: "2025-02-01",
    readingTime: "5 min",
    image: "/images/posts/healthy-habits.jpg",
    tags: ["Health", "Habits", "Lifestyle"],
    content: `Simple daily habits can dramatically improve your health. Here are ten proven tips to enhance your physical and mental well-being.`,
  },
  {
    id: "health-post-2",
    title: "Nutrition Myths Busted",
    description: "Debunking common diet misconceptions with real science.",
    category: "health",
    author: "David Kim",
    publishedDate: "2025-03-11",
    readingTime: "4 min",
    image: "/images/posts/nutrition-myths.jpg",
    tags: ["Nutrition", "Myths", "Diet"],
    content: `There's a lot of misinformation about food. We tackle some of the most persistent myths and explain what's actually true.`,
  },
  {
    id: "health-post-3",
    title: "Home Workouts for Busy People",
    description: "Effective routines to stay fit without going to the gym.",
    category: "health",
    author: "Laura Nguyen",
    publishedDate: "2025-01-15",
    readingTime: "6 min",
    image: "/images/posts/home-workouts.jpg",
    tags: ["Fitness", "Workouts", "Home"],
    content: `No time for the gym? These at-home workouts can keep you fit with just 15–30 minutes a day.`,
  },
  {
    id: "health-post-4",
    title: "The Science of Sleep",
    description: "Why quality sleep matters more than you think.",
    category: "health",
    author: "Carlos Martinez",
    publishedDate: "2025-04-02",
    readingTime: "5 min",
    image: "/images/posts/sleep-science.jpg",
    tags: ["Sleep", "Health", "Science"],
    content: `Learn how sleep impacts your health and how to improve your sleep cycle using science-backed strategies.`,
  },

  // 🌍 Travel
  {
    id: "travel-post-1",
    title: "Top 5 Affordable Destinations in 2025",
    description: "Travel on a budget without missing out on adventure.",
    category: "travel",
    author: "Anna Petrova",
    publishedDate: "2025-01-18",
    readingTime: "4 min",
    image: "/images/posts/affordable-destinations.jpg",
    tags: ["Travel", "Budget", "Destinations"],
    content: `Explore amazing places around the world without breaking the bank. Here are 5 destinations where your money goes further.`,
  },
  {
    id: "travel-post-2",
    title: "Backpacking Across Europe: What You Need",
    description: "Essential tips for an unforgettable European trip.",
    category: "travel",
    author: "Tom Harris",
    publishedDate: "2025-03-01",
    readingTime: "6 min",
    image: "/images/posts/backpacking-europe.jpg",
    tags: ["Backpacking", "Europe", "Adventure"],
    content: `If you're planning to backpack through Europe, here are the must-have items and hacks to make your trip smooth and fun.`,
  },
  {
    id: "travel-post-3",
    title: "Digital Nomad Guide: Working While Traveling",
    description: "How to balance remote work and world exploration.",
    category: "travel",
    author: "Sophia Tan",
    publishedDate: "2025-02-22",
    readingTime: "7 min",
    image: "/images/posts/digital-nomad.jpg",
    tags: ["Remote Work", "Lifestyle", "Nomad"],
    content: `More people are working from exotic locations. Here's how you can set up your digital workspace and stay productive on the road.`,
  },
  {
    id: "travel-post-4",
    title: "Cultural Etiquette Around the World",
    description: "Respect local customs wherever you go.",
    category: "travel",
    author: "Mark Ishikawa",
    publishedDate: "2025-04-05",
    readingTime: "5 min",
    image: "/images/posts/cultural-etiquette.jpg",
    tags: ["Culture", "Travel Tips", "Global"],
    content: `Every country has its own rules of etiquette. Learn the dos and don’ts before you travel to avoid cultural misunderstandings.`,
  },

  // 💰 Finance
  {
    id: "finance-post-1",
    title: "Beginner's Guide to Investing",
    description: "Simple strategies to grow your money long-term.",
    category: "finance",
    author: "Rachel Green",
    publishedDate: "2025-02-10",
    readingTime: "6 min",
    image: "/images/posts/investing-guide.jpg",
    tags: ["Finance", "Investing", "Money"],
    content: `Investing doesn’t have to be hard. This beginner-friendly guide walks you through the basics of stocks, bonds, and diversification.`,
  },
  {
    id: "finance-post-2",
    title: "Budgeting Like a Pro",
    description: "Track your spending and save smarter.",
    category: "finance",
    author: "Liam Shaw",
    publishedDate: "2025-01-30",
    readingTime: "5 min",
    image: "/images/posts/budgeting.jpg",
    tags: ["Budget", "Finance", "Savings"],
    content: `Want to control your finances better? Learn how to create a realistic budget and stick to it every month.`,
  },
  {
    id: "finance-post-3",
    title: "Cryptocurrency in 2025",
    description: "Is crypto still a good investment? Find out here.",
    category: "finance",
    author: "Nina Das",
    publishedDate: "2025-03-05",
    readingTime: "7 min",
    image: "/images/posts/crypto-2025.jpg",
    tags: ["Crypto", "Blockchain", "Finance"],
    content: `Crypto continues to be a hot topic in 2025. Here's what investors need to know before jumping into digital assets.`,
  },
  {
    id: "finance-post-4",
    title: "Avoiding Common Financial Scams",
    description: "Stay protected by learning how scammers trick you.",
    category: "finance",
    author: "Ahmed Farouk",
    publishedDate: "2025-04-08",
    readingTime: "5 min",
    image: "/images/posts/financial-scams.jpg",
    tags: ["Fraud", "Money", "Security"],
    content: `Scams are becoming more sophisticated. Learn how to identify and avoid common traps that can cost you thousands.`,
  },
];
